#!/usr/bin/env bash

# Echos the tag of Terragrunt latest release without the 'v' prefix

latest_release="https://api.github.com/repos/gruntwork-io/terragrunt/releases/latest"

res=$(curl -s "$latest_release" | jq -r '.tag_name' | cut -c 2-)

echo "$res"
